<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20220421074938 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // стили
        $this->addSql('INSERT INTO style (id, name) VALUES (1, "Классический");');
        $this->addSql('INSERT INTO style (id, name) VALUES (2, "Кэжуал");');
        $this->addSql('INSERT INTO style (id, name) VALUES (3, "Спортивный");');
        $this->addSql('INSERT INTO style (id, name) VALUES (4, "Минимализм");');
        $this->addSql('INSERT INTO style (id, name) VALUES (5, "Гламур");');
        $this->addSql('INSERT INTO style (id, name) VALUES (6, "Гранж");');
        //  признаки
        $this->addSql('INSERT INTO feature (id, name) VALUES (1, "Половой тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (2, "Тип ношения");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (3, "Функциональный тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (4, "Климатический тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (5, "Эксплуатационный тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (6, "Технология изготовления");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (7, "Производственный тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (8, "Материал");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (9, "Цвет");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (10, "Размер");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (11, "Практичность");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (12, "Художественный тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (13, "Экономический тип");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (14, "Тип ассортимента");');
        $this->addSql('INSERT INTO feature (id, name) VALUES (15, "Дополнительные функции");');
        // значения признаков
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (1, "Половой тип","Мужская");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (2, "Половой тип","Женская");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (3, "Половой тип","Унисекс");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (4, "Тип ношения","Плечевая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (5, "Тип ношения","Поясная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (6, "Функциональный тип","Верхняя");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (7, "Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (8, "Функциональный тип","Корсетные изделия");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (9, "Функциональный тип","Постельное белье");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (10, "Функциональный тип","Нижняя");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (11, "Климатический тип","Летняя");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (12, "Климатический тип","Зимняя");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (13, "Климатический тип","Всесезонная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (14, "Климатический тип","Демисезонная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (15, "Эксплуатационный тип","Бытовая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (16, "Эксплуатационный тип","Производственная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (17, "Технология изготовления","Швейная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (18, "Технология изготовления","Трикотажная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (19, "Технология изготовления","Валяная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (20, "Производственный тип","Массовая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (21, "Производственный тип","На заказ");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (22, "Материал","Меховая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (23, "Материал","Кожаная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (24, "Материал","Тканевая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (25, "Материал","Перо-пуховая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (26, "Материал","Полимерная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (27, "Цвет","Черная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (28, "Цвет","Белая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (29, "Цвет","Цветная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (30, "Цвет","Разноцветная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (31, "Размер","Скинни");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (32, "Размер","Оверсайз");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (33, "Размер","Классический");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (34, "Практичность","0");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (35, "Практичность","0.5");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (36, "Практичность","1");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (37, "Художественный тип","С рисунками");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (38, "Художественный тип","С нашивками");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (39, "Экономический тип","0 - 10000р");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (40, "Экономический тип","10000р - 20000р");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (41, "Экономический тип","20000р - более");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (42, "Тип ассортимента","Пальто");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (43, "Тип ассортимента","Куртка");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (44, "Тип ассортимента","Брюки");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (45, "Тип ассортимента","Шляпа");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (46, "Тип ассортимента","Футболка");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (47, "Тип ассортимента","Штаны");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (48, "Тип ассортимента","Худи");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (49, "Тип ассортимента","Ремень");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (50, "Тип ассортимента","Перчатки");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (51, "Тип ассортимента","Кофта");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (52, "Дополнительные функции","Солнцезащитная");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (53, "Дополнительные функции","Водонепроницаемая");');
        $this->addSql('INSERT INTO feature_value (id, feature_name, value) VALUES (54, "Дополнительные функции","Теплоудерживающая");');
        // признаки класса
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (1, "Половой тип","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (2, "Тип ношения","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (3, "Функциональный тип","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (4, "Технология изготовления","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (5, "Производственный тип","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (6, "Материал","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (7, "Цвет","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (8, "Размер","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (9, "Практичность","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (10, "Экономический тип","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (11, "Тип ассортимента","Классический");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (12, "Половой тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (13, "Тип ношения","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (14, "Функциональный тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (15, "Климатический тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (16, "Эксплуатационный тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (17, "Технология изготовления","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (18, "Производственный тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (19, "Материал","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (20, "Цвет","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (21, "Размер","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (22, "Практичность","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (23, "Художественный тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (24, "Экономический тип","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (25, "Тип ассортимента","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (26, "Дополнительные функции","Кэжуал");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (27, "Половой тип","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (28, "Тип ношения","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (29, "Функциональный тип","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (30, "Эксплуатационный тип","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (31, "Технология изготовления","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (32, "Производственный тип","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (33, "Материал","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (34, "Цвет","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (35, "Размер","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (36, "Практичность","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (37, "Художественный тип","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (38, "Экономический тип","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (39, "Тип ассортимента","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (40, "Дополнительные функции","Спортивный");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (41, "Половой тип","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (42, "Тип ношения","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (43, "Функциональный тип","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (44, "Климатический тип","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (45, "Эксплуатационный тип","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (46, "Технология изготовления","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (47, "Производственный тип","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (48, "Материал","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (49, "Цвет","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (50, "Размер","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (51, "Практичность","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (52, "Экономический тип","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (53, "Тип ассортимента","Минимализм");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (55, "Половой тип","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (56, "Тип ношения","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (57, "Функциональный тип","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (58, "Климатический тип","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (59, "Технология изготовления","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (60, "Производственный тип","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (61, "Материал","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (62, "Цвет","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (63, "Размер","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (64, "Практичность","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (65, "Экономический тип","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (66, "Тип ассортимента","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (67, "Дополнительные функции","Гламур");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (68, "Тип ношения","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (69, "Функциональный тип","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (70, "Климатический тип","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (71, "Эксплуатационный тип","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (72, "Технология изготовления","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (73, "Производственный тип","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (74, "Материал","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (75, "Цвет","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (76, "Размер","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (77, "Практичность","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (78, "Художественный тип","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (79, "Экономический тип","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (80, "Тип ассортимента","Гранж");');
        $this->addSql('INSERT INTO style_feature (id, feature_name, class_name) VALUES (81, "Дополнительные функции","Гранж");');
        // значения признаков класса
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (1, "Классический","Половой тип","Мужская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (2, "Классический","Половой тип","Женская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (3, "Классический","Тип ношения","Плечевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (4, "Классический","Тип ношения","Поясная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (5, "Классический","Функциональный тип","Верхняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (6, "Классический","Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (7, "Классический","Функциональный тип","Корсетные изделия");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (8, "Классический","Технология изготовления","Швейная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (9, "Классический","Производственный тип","На заказ");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (10, "Классический","Материал","Тканевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (11, "Классический","Материал","Полимерная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (12, "Классический","Цвет","Черная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (13, "Классический","Цвет","Белая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (14, "Классический","Размер","Классический");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (15, "Классический","Практичность","1");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (16, "Классический","Экономический тип","20000р - более");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (17, "Классический","Тип ассортимента","Пальто");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (18, "Классический","Тип ассортимента","Брюки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (19, "Классический","Тип ассортимента","Ремень");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (20, "Классический","Тип ассортимента","Перчатки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (21, "Кэжуал","Половой тип","Мужская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (22, "Кэжуал","Половой тип","Женская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (23, "Кэжуал","Половой тип","Унисекс");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (24, "Кэжуал","Тип ношения","Плечевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (25, "Кэжуал","Тип ношения","Поясная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (26, "Кэжуал","Функциональный тип","Верхняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (27, "Кэжуал","Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (28, "Кэжуал","Функциональный тип","Нижняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (29, "Кэжуал","Климатический тип","Летняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (30, "Кэжуал","Климатический тип","Зимняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (31, "Кэжуал","Климатический тип","Всесезонная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (32, "Кэжуал","Климатический тип","Демисезонная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (33, "Кэжуал","Эксплуатационный тип","Бытовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (34, "Кэжуал","Эксплуатационный тип","Производственная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (35, "Кэжуал","Технология изготовления","Трикотажная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (36, "Кэжуал","Технология изготовления","Валяная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (37, "Кэжуал","Производственный тип","Массовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (38, "Кэжуал","Материал","Меховая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (39, "Кэжуал","Материал","Кожаная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (40, "Кэжуал","Материал","Тканевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (41, "Кэжуал","Цвет","Черная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (42, "Кэжуал","Цвет","Белая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (43, "Кэжуал","Цвет","Цветная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (44, "Кэжуал","Цвет","Разноцветная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (45, "Кэжуал","Размер","Скинни");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (46, "Кэжуал","Размер","Оверсайз");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (47, "Кэжуал","Размер","Классический");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (48, "Кэжуал","Практичность","0.5");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (49, "Кэжуал","Художественный тип","С рисунками");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (50, "Кэжуал","Художественный тип","С нашивками");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (51, "Кэжуал","Экономический тип","0 - 10000р");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (52, "Кэжуал","Экономический тип","10000р - 20000р");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (53, "Кэжуал","Тип ассортимента","Пальто");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (54, "Кэжуал","Тип ассортимента","Куртка");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (55, "Кэжуал","Тип ассортимента","Брюки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (56, "Кэжуал","Тип ассортимента","Шляпа");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (57, "Кэжуал","Тип ассортимента","Футболка");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (58, "Кэжуал","Тип ассортимента","Худи");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (59, "Кэжуал","Тип ассортимента","Ремень");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (60, "Кэжуал","Тип ассортимента","Перчатки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (61, "Кэжуал","Тип ассортимента","Кофта");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (62, "Кэжуал","Дополнительные функции","Теплоудерживающая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (63, "Спортивный","Половой тип","Мужская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (64, "Спортивный","Половой тип","Женская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (65, "Спортивный","Половой тип","Унисекс");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (66, "Спортивный","Тип ношения","Плечевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (67, "Спортивный","Тип ношения","Поясная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (68, "Спортивный","Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (69, "Спортивный","Функциональный тип","Нижняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (70, "Спортивный","Эксплуатационный тип","Бытовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (71, "Спортивный","Эксплуатационный тип","Производственная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (72, "Спортивный","Технология изготовления","Трикотажная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (73, "Спортивный","Производственный тип","Массовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (74, "Спортивный","Материал","Тканевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (75, "Спортивный","Материал","Полимерная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (76, "Спортивный","Цвет","Черная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (77, "Спортивный","Цвет","Цветная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (78, "Спортивный","Размер","Классический");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (79, "Спортивный","Практичность","1");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (80, "Спортивный","Художественный тип","С рисунками");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (81, "Спортивный","Экономический тип","0 - 10000р");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (82, "Спортивный","Тип ассортимента","Куртка");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (83, "Спортивный","Тип ассортимента","Брюки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (84, "Спортивный","Тип ассортимента","Футболка");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (85, "Спортивный","Тип ассортимента","Худи");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (86, "Спортивный","Дополнительные функции","Водонепроницаемая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (87, "Спортивный","Дополнительные функции","Теплоудерживающая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (88, "Минимализм","Половой тип","Мужская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (89, "Минимализм","Половой тип","Женская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (90, "Минимализм","Половой тип","Унисекс");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (91, "Минимализм","Тип ношения","Плечевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (92, "Минимализм","Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (93, "Минимализм","Климатический тип","Летняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (94, "Минимализм","Эксплуатационный тип","Бытовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (95, "Минимализм","Технология изготовления","Трикотажная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (96, "Минимализм","Производственный тип","Массовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (97, "Минимализм","Материал","Меховая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (98, "Минимализм","Материал","Тканевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (99, "Минимализм","Цвет","Черная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (100, "Минимализм","Цвет","Белая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (101, "Минимализм","Цвет","Цветная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (102, "Минимализм","Размер","Скинни");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (103, "Минимализм","Размер","Классический");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (104, "Минимализм","Практичность","0.5");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (105, "Минимализм","Экономический тип","10000р - 20000р");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (106, "Минимализм","Тип ассортимента","Пальто");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (107, "Минимализм","Тип ассортимента","Футболка");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (108, "Минимализм","Тип ассортимента","Кофта");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (109, "Гламур","Половой тип","Женская");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (110, "Гламур","Тип ношения","Плечевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (111, "Гламур","Функциональный тип","Верхняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (112, "Гламур","Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (113, "Гламур","Функциональный тип","Корсетные изделия");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (114, "Гламур","Климатический тип","Зимняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (115, "Гламур","Климатический тип","Демисезонная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (116, "Гламур","Технология изготовления","Швейная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (117, "Гламур","Технология изготовления","Валяная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (118, "Гламур","Производственный тип","На заказ");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (119, "Гламур","Материал","Меховая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (120, "Гламур","Материал","Перо-пуховая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (121, "Гламур","Цвет","Черная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (122, "Гламур","Цвет","Белая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (123, "Гламур","Размер","Оверсайз");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (124, "Гламур","Размер","Классический");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (125, "Гламур","Практичность","0");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (126, "Гламур","Экономический тип","20000р - более");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (127, "Гламур","Тип ассортимента","Пальто");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (128, "Гламур","Тип ассортимента","Куртка");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (129, "Гламур","Тип ассортимента","Шляпа");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (130, "Гламур","Тип ассортимента","Перчатки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (131, "Гламур","Тип ассортимента","Кофта");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (132, "Гламур","Дополнительные функции","Теплоудерживающая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (133, "Гранж","Тип ношения","Поясная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (134, "Гранж","Функциональный тип","Верхняя");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (135, "Гранж","Функциональный тип","Верхняя легкая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (136, "Гранж","Климатический тип","Всесезонная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (137, "Гранж","Эксплуатационный тип","Бытовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (138, "Гранж","Эксплуатационный тип","Производственная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (139, "Гранж","Технология изготовления","Трикотажная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (140, "Гранж","Производственный тип","Массовая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (141, "Гранж","Производственный тип","На заказ");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (142, "Гранж","Материал","Кожаная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (143, "Гранж","Материал","Тканевая");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (144, "Гранж","Цвет","Черная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (145, "Гранж","Цвет","Цветная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (146, "Гранж","Цвет","Разноцветная");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (147, "Гранж","Размер","Скинни");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (148, "Гранж","Размер","Оверсайз");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (149, "Гранж","Размер","Классический");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (150, "Гранж","Практичность","0");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (151, "Гранж","Художественный тип","С рисунками");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (152, "Гранж","Художественный тип","С нашивками");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (153, "Гранж","Экономический тип","0 - 10000р");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (154, "Гранж","Экономический тип","10000р - 20000р");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (155, "Гранж","Тип ассортимента","Брюки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (156, "Гранж","Тип ассортимента","Ремень");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (157, "Гранж","Тип ассортимента","Перчатки");');
        $this->addSql('INSERT INTO style_feature_value (id, class_name, feature_name, feature_value) VALUES (158, "Гранж","Дополнительные функции","Солнцезащитная");');

    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs

    }
}
